"use client";

import { Calendar, Code, Download, FileText } from "lucide-react";
import { useRef, useState } from "react";
import { ScreenWidget, WidgetCard } from "./WidgetCard";

// Re-export types for backward compatibility
export type { CardColorTheme, ScreenWidget, WidgetType } from "./WidgetCard";

export interface ScreenProps {
  title?: string;
  subtitle?: string;
  updatedAt?: string;
  columns?: number;
  widgets: ScreenWidget[];
}

export default function LLMScreen({
  title = "AI Canvas",
  subtitle = "Content generated by AI",
  updatedAt,
  widgets = [],
  columns = 4,
}: ScreenProps) {
  const [showDebug, setShowDebug] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const activeWidgets = widgets;

  const generateHTMLContent = () => {
    if (!contentRef.current) return null;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; }

    @media print {
      @page {
        size: A4 landscape;
        margin: 10mm;
      }
      body {
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
        padding: 0 !important;
      }
      .max-w-7xl {
        max-width: 100% !important;
        width: 100% !important;
        margin: 0 !important;
      }
      .grid {
        display: grid !important;
        grid-template-columns: repeat(${columns}, minmax(0, 1fr)) !important;
        gap: 1.5rem !important;
        width: 100% !important;
      }
      .col-span-1 { grid-column: span 1 / span 1 !important; }
      .col-span-2, .md\\:col-span-2 { grid-column: span 2 / span 2 !important; }
      .col-span-3, .md\\:col-span-3 { grid-column: span 3 / span 3 !important; }
      .col-span-4, .md\\:col-span-4 { grid-column: span 4 / span 4 !important; }

      /* Prevent widgets from breaking across pages */
      .grid > * {
        break-inside: avoid !important;
        page-break-inside: avoid !important;
      }
    }
  </style>
</head>
<body class="min-h-screen bg-slate-50 p-6 md:p-8 text-slate-900">
  <div class="max-w-7xl mx-auto mb-8">
    <h1 class="text-3xl font-bold text-slate-900 tracking-tight">${title}</h1>
    <p class="text-slate-500 mt-2 text-lg">${subtitle}</p>
  </div>
  ${contentRef.current.outerHTML}
</body>
</html>`;
  };

  const handleExportHTML = () => {
    const htmlContent = generateHTMLContent();
    if (!htmlContent) return;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${title.replace(/\s+/g, "_").toLowerCase()}_export.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleExportPDF = () => {
    const htmlContent = generateHTMLContent();
    if (!htmlContent) return;

    // Open a new window with the HTML content
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      alert("Please allow popups to export PDF");
      return;
    }

    printWindow.document.write(htmlContent);
    printWindow.document.close();

    // Wait for Tailwind CSS to load, then trigger print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 500);
    };
  };

  return (
    <div className="min-h-screen bg-slate-50 p-6 md:p-8 font-sans text-slate-900">
      {/* Header Section */}
      <div className="max-w-7xl mx-auto mb-8 flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight">
            {title}
          </h1>
          <p className="text-slate-500 mt-2 text-lg">{subtitle}</p>
        </div>
        <div className="flex items-center gap-3">
          {updatedAt && (
            <div className="flex items-center text-sm text-slate-400 bg-white px-3 py-1.5 rounded-md border border-slate-200 shadow-sm">
              <Calendar className="w-4 h-4 mr-2" />
              {new Date(updatedAt).toLocaleDateString()}
            </div>
          )}
          <button
            onClick={() => setShowDebug(!showDebug)}
            className={`p-2 rounded-md border transition-colors ${
              showDebug
                ? "bg-slate-800 text-white border-slate-800"
                : "bg-white text-slate-500 border-slate-200 hover:bg-slate-50"
            }`}
            title="Toggle JSON Debug View"
          >
            <Code className="w-5 h-5" />
          </button>
          <button
            onClick={handleExportHTML}
            className="p-2 rounded-md border transition-colors bg-white text-slate-500 border-slate-200 hover:bg-slate-50"
            title="Export as HTML"
          >
            <Download className="w-5 h-5" />
          </button>
          <button
            onClick={handleExportPDF}
            className="p-2 rounded-md border transition-colors bg-white text-slate-500 border-slate-200 hover:bg-slate-50"
            title="Export as PDF"
          >
            <FileText className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* Grid Layout */}
      <div
        ref={contentRef}
        className={`max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-${columns} gap-6`}
      >
        {activeWidgets.map((widget) => (
          <WidgetCard key={widget.id} widget={widget} />
        ))}
      </div>

      {/* Debug View */}
      {showDebug && (
        <div className="max-w-7xl mx-auto mt-12 p-6 bg-slate-900 rounded-xl overflow-hidden">
          <h3 className="text-slate-400 text-sm font-mono mb-4 uppercase tracking-wider">
            LLM Generated Configuration
          </h3>
          <pre className="text-emerald-400 font-mono text-xs overflow-x-auto">
            {JSON.stringify(
              { title, subtitle, widgets: activeWidgets },
              null,
              2
            )}
          </pre>
        </div>
      )}
    </div>
  );
}
